name : Upload cloudresume to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
    with:
      args: --acl public-read --follow-symlinks --delete
    env:
      AWS_S3_BUCKET: ${{ secerts.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secerts.AWS_ACCESS_KEY_ID }}
      AWS_SECERT_ACCESS_KEY: ${{ secerts.AWS_SECERT_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
      SOURCE_DIR: 'cloud-resume'